import type { FirebaseCategory } from '../types/firebase';

// Seed data for categories (without timestamps - added during seeding)
export type CategorySeed = Omit<FirebaseCategory, 'createdAt' | 'updatedAt'>;

export const categoriesSeed: CategorySeed[] = [
  {
    id: 'immigration',
    slug: 'immigration',
    name: 'Immigration & Emigration',
    nameSi: 'ආගමන හා විගමන',
    nameTa: 'குடிவரவு மற்றும் குடியகல்வு',
    description: 'Passports, visas, travel documents, and citizenship',
    descriptionSi: 'ගමන් බලපත්‍ර, වීසා, සංචාරක ලේඛන සහ පුරවැසිභාවය',
    descriptionTa: 'கடவுச்சீட்டுகள், விசாக்கள், பயண ஆவணங்கள் மற்றும் குடியுரிமை',
    icon: 'passport',
    color: '#1E40AF',
    order: 1,
    formCount: 0,
    isActive: true,
  },
  {
    id: 'motor-vehicles',
    slug: 'motor-vehicles',
    name: 'Motor Traffic',
    nameSi: 'මෝටර් රථ ගමනාගමන',
    nameTa: 'மோட்டார் போக்குவரத்து',
    description: 'Vehicle registration, driving licenses, and road permits',
    descriptionSi: 'වාහන ලියාපදිංචිය, රියදුරු බලපත්‍ර සහ මාර්ග බලපත්‍ර',
    descriptionTa: 'வாகன பதிவு, ஓட்டுநர் உரிமம் மற்றும் சாலை அனுமதிகள்',
    icon: 'car',
    color: '#059669',
    order: 2,
    formCount: 0,
    isActive: true,
  },
  {
    id: 'disaster-relief',
    slug: 'disaster-relief',
    name: 'Disaster Relief',
    nameSi: 'ආපදා සහන',
    nameTa: 'பேரிடர் நிவாரணம்',
    description: 'Natural disaster relief applications and assistance',
    descriptionSi: 'ස්වාභාවික ආපදා සහන අයදුම්පත් සහ සහාය',
    descriptionTa: 'இயற்கை பேரிடர் நிவாரண விண்ணப்பங்கள் மற்றும் உதவி',
    icon: 'shield',
    color: '#DC2626',
    order: 3,
    formCount: 0,
    isActive: true,
  },
  {
    id: 'police-clearance',
    slug: 'police-clearance',
    name: 'Police & Security',
    nameSi: 'පොලිසිය සහ ආරක්ෂාව',
    nameTa: 'காவல்துறை மற்றும் பாதுகாப்பு',
    description: 'Police clearance certificates and security checks',
    descriptionSi: 'පොලිස් නිශ්කාෂණ සහතික සහ ආරක්ෂක පරීක්ෂා',
    descriptionTa: 'காவல்துறை அனுமதிச் சான்றிதழ்கள் மற்றும் பாதுகாப்பு சோதனைகள்',
    icon: 'shield-check',
    color: '#7C3AED',
    order: 4,
    formCount: 0,
    isActive: true,
  },
  {
    id: 'land-registration',
    slug: 'land-registration',
    name: 'Land & Property',
    nameSi: 'ඉඩම් සහ දේපල',
    nameTa: 'நிலம் மற்றும் சொத்து',
    description: 'Land registration, deeds, and property documents',
    descriptionSi: 'ඉඩම් ලියාපදිංචිය, ඔප්පු සහ දේපල ලේඛන',
    descriptionTa: 'நில பதிவு, பத்திரங்கள் மற்றும் சொத்து ஆவணங்கள்',
    icon: 'home',
    color: '#CA8A04',
    order: 5,
    formCount: 0,
    isActive: true,
  },
  {
    id: 'civil-registration',
    slug: 'civil-registration',
    name: 'Civil Registration',
    nameSi: 'සිවිල් ලියාපදිංචිය',
    nameTa: 'சிவில் பதிவு',
    description: 'Birth, death, and marriage certificates',
    descriptionSi: 'උප්පැන්න, මරණ සහ විවාහ සහතික',
    descriptionTa: 'பிறப்பு, இறப்பு மற்றும் திருமண சான்றிதழ்கள்',
    icon: 'file-text',
    color: '#0891B2',
    order: 6,
    formCount: 0,
    isActive: true,
  },
  {
    id: 'education',
    slug: 'education',
    name: 'Education',
    nameSi: 'අධ්‍යාපනය',
    nameTa: 'கல்வி',
    description: 'School admissions, scholarships, and educational certificates',
    descriptionSi: 'පාසල් ඇතුළත් කිරීම්, ශිෂ්‍යත්ව සහ අධ්‍යාපන සහතික',
    descriptionTa: 'பள்ளி சேர்க்கைகள், உதவித்தொகைகள் மற்றும் கல்வி சான்றிதழ்கள்',
    icon: 'graduation-cap',
    color: '#2563EB',
    order: 7,
    formCount: 0,
    isActive: true,
  },
  {
    id: 'health',
    slug: 'health',
    name: 'Health Services',
    nameSi: 'සෞඛ්‍ය සේවා',
    nameTa: 'சுகாதார சேவைகள்',
    description: 'Medical certificates, health cards, and hospital forms',
    descriptionSi: 'වෛද්‍ය සහතික, සෞඛ්‍ය කාඩ්පත් සහ රෝහල් පෝරම',
    descriptionTa: 'மருத்துவ சான்றிதழ்கள், சுகாதார அட்டைகள் மற்றும் மருத்துவமனை படிவங்கள்',
    icon: 'heart-pulse',
    color: '#E11D48',
    order: 8,
    formCount: 0,
    isActive: true,
  },
  {
    id: 'taxation',
    slug: 'taxation',
    name: 'Taxation',
    nameSi: 'බදු',
    nameTa: 'வரிவிதிப்பு',
    description: 'Income tax, VAT, and other tax-related forms',
    descriptionSi: 'ආදායම් බදු, වැට් සහ අනෙකුත් බදු ආශ්‍රිත පෝරම',
    descriptionTa: 'வருமான வரி, மதிப்பு கூட்டு வரி மற்றும் பிற வரி தொடர்பான படிவங்கள்',
    icon: 'calculator',
    color: '#4F46E5',
    order: 9,
    formCount: 0,
    isActive: true,
  },
  {
    id: 'social-services',
    slug: 'social-services',
    name: 'Social Services',
    nameSi: 'සමාජ සේවා',
    nameTa: 'சமூக சேவைகள்',
    description: 'Pensions, welfare, and social assistance programs',
    descriptionSi: 'විශ්‍රාම වැටුප්, සුබසාධන සහ සමාජ සහාය වැඩසටහන්',
    descriptionTa: 'ஓய்வூதியங்கள், நலன்புரி மற்றும் சமூக உதவி திட்டங்கள்',
    icon: 'users',
    color: '#DB2777',
    order: 10,
    formCount: 0,
    isActive: true,
  },
  {
    id: 'business',
    slug: 'business',
    name: 'Business & Commerce',
    nameSi: 'ව්‍යාපාර සහ වාණිජ්‍ය',
    nameTa: 'வணிகம் மற்றும் வர்த்தகம்',
    description: 'Business registration, licenses, and permits',
    descriptionSi: 'ව්‍යාපාර ලියාපදිංචිය, බලපත්‍ර සහ අවසර',
    descriptionTa: 'வணிக பதிவு, உரிமங்கள் மற்றும் அனுமதிகள்',
    icon: 'briefcase',
    color: '#EA580C',
    order: 11,
    formCount: 0,
    isActive: true,
  },
  {
    id: 'utilities',
    slug: 'utilities',
    name: 'Utilities',
    nameSi: 'උපයෝගිතා',
    nameTa: 'பயன்பாடுகள்',
    description: 'Electricity, water, and telecommunications services',
    descriptionSi: 'විදුලිය, ජලය සහ විදුලි සංදේශ සේවා',
    descriptionTa: 'மின்சாரம், நீர் மற்றும் தொலைத்தொடர்பு சேவைகள்',
    icon: 'zap',
    color: '#0D9488',
    order: 12,
    formCount: 0,
    isActive: true,
  },
];
