import type { FirebaseInstitution } from '../types/firebase';

// Seed data for institutions (without timestamps - added during seeding)
export type InstitutionSeed = Omit<FirebaseInstitution, 'createdAt' | 'updatedAt'>;

export const institutionsSeed: InstitutionSeed[] = [
  // Ministries
  {
    id: 'ministry-public-security',
    name: 'Ministry of Public Security',
    nameSi: 'මහජන ආරක්ෂක අමාත්‍යාංශය',
    nameTa: 'பொது பாதுகாப்பு அமைச்சு',
    description: 'Responsible for internal security and law enforcement',
    type: 'ministry',
    website: 'https://www.pubsec.gov.lk',
    formCount: 0,
    isActive: true,
  },
  {
    id: 'ministry-transport',
    name: 'Ministry of Transport',
    nameSi: 'ප්‍රවාහන අමාත්‍යාංශය',
    nameTa: 'போக்குவரத்து அமைச்சு',
    description: 'Responsible for transport and motor traffic',
    type: 'ministry',
    website: 'https://www.transport.gov.lk',
    formCount: 0,
    isActive: true,
  },
  {
    id: 'ministry-home-affairs',
    name: 'Ministry of Home Affairs',
    nameSi: 'ස්වදේශ කටයුතු අමාත්‍යාංශය',
    nameTa: 'உள்நாட்டு அலுவல்கள் அமைச்சு',
    description: 'Responsible for civil registration and internal affairs',
    type: 'ministry',
    formCount: 0,
    isActive: true,
  },

  // Departments
  {
    id: 'dept-immigration',
    name: 'Department of Immigration and Emigration',
    nameSi: 'ආගමන හා විගමන දෙපාර්තමේන්තුව',
    nameTa: 'குடிவரவு மற்றும் குடியகல்வு திணைக்களம்',
    description: 'Issues passports, visas, and travel documents',
    type: 'department',
    parentInstitutionId: 'ministry-public-security',
    website: 'https://www.immigration.gov.lk',
    email: 'controller@immigration.gov.lk',
    phone: '+94 11 5329 000',
    address: '41, Ananda Rajakaruna Mawatha, Colombo 10',
    formCount: 0,
    isActive: true,
  },
  {
    id: 'dept-motor-traffic',
    name: 'Department of Motor Traffic',
    nameSi: 'මෝටර් රථ ප්‍රවාහන දෙපාර්තමේන්තුව',
    nameTa: 'மோட்டார் போக்குவரத்து திணைக்களம்',
    description: 'Vehicle registration and driving licenses',
    type: 'department',
    parentInstitutionId: 'ministry-transport',
    website: 'https://www.motortraffic.gov.lk',
    email: 'info@motortraffic.gov.lk',
    phone: '+94 11 2694 331',
    address: '341, Elvitigala Mawatha, Colombo 05',
    formCount: 0,
    isActive: true,
  },
  {
    id: 'dept-registrar-general',
    name: 'Registrar General\'s Department',
    nameSi: 'රෙජිස්ට්‍රාර් ජනරාල් දෙපාර්තමේන්තුව',
    nameTa: 'பதிவாளர் நாயகம் திணைக்களம்',
    description: 'Birth, death, and marriage registration',
    type: 'department',
    parentInstitutionId: 'ministry-home-affairs',
    website: 'https://www.rgd.gov.lk',
    phone: '+94 11 2 877 208',
    address: '234/A3, Denzil Kobbekaduwa Mawatha, Battaramulla',
    formCount: 0,
    isActive: true,
  },
  {
    id: 'dept-police',
    name: 'Sri Lanka Police',
    nameSi: 'ශ්‍රී ලංකා පොලිසිය',
    nameTa: 'இலங்கை பொலிஸ்',
    description: 'Law enforcement and police services',
    type: 'department',
    parentInstitutionId: 'ministry-public-security',
    website: 'https://www.police.lk',
    phone: '+94 11 2 421 111',
    address: 'Police Headquarters, Colombo 01',
    formCount: 0,
    isActive: true,
  },

  // Authorities & Centers
  {
    id: 'ndrsc',
    name: 'National Disaster Relief Services Centre',
    nameSi: 'ජාතික ආපදා සහන සේවා මධ්‍යස්ථානය',
    nameTa: 'தேசிய அனர்த்த நிவாரண சேவைகள் நிலையம்',
    description: 'Disaster relief and emergency assistance',
    type: 'authority',
    website: 'https://www.ndrsc.gov.lk',
    phone: '+94 11 2 670 070',
    formCount: 0,
    isActive: true,
  },
  {
    id: 'inland-revenue',
    name: 'Inland Revenue Department',
    nameSi: 'දේශීය ආදායම් දෙපාර්තමේන්තුව',
    nameTa: 'உள்நாட்டு இறைவரி திணைக்களம்',
    description: 'Tax collection and revenue services',
    type: 'department',
    website: 'https://www.ird.gov.lk',
    email: 'cgir@ird.gov.lk',
    phone: '+94 11 2 134 134',
    address: 'Inland Revenue Building, Sir Chittampalam A. Gardiner Mawatha, Colombo 02',
    formCount: 0,
    isActive: true,
  },
  {
    id: 'land-registry',
    name: 'Land Registry Department',
    nameSi: 'ඉඩම් රෙජිස්ට්‍රාර් දෙපාර්තමේන්තුව',
    nameTa: 'நில பதிவாளர் திணைக்களம்',
    description: 'Land registration and deed services',
    type: 'department',
    website: 'https://www.landregistry.gov.lk',
    formCount: 0,
    isActive: true,
  },
  {
    id: 'dept-pensions',
    name: 'Department of Pensions',
    nameSi: 'විශ්‍රාම වැටුප් දෙපාර්තමේන්තුව',
    nameTa: 'ஓய்வூதியத் திணைக்களம்',
    description: 'Government pension services',
    type: 'department',
    website: 'https://www.pensions.gov.lk',
    phone: '+94 11 2 369 214',
    formCount: 0,
    isActive: true,
  },
  {
    id: 'dept-examinations',
    name: 'Department of Examinations',
    nameSi: 'විභාග දෙපාර්තමේන්තුව',
    nameTa: 'பரீட்சைகள் திணைக்களம்',
    description: 'National examinations and certifications',
    type: 'department',
    website: 'https://www.doenets.lk',
    phone: '+94 11 2 784 208',
    address: 'Pelawatta, Battaramulla',
    formCount: 0,
    isActive: true,
  },

  // Embassies (for overseas citizens)
  {
    id: 'embassy-austria',
    name: 'Embassy of Sri Lanka - Vienna',
    nameSi: 'ශ්‍රී ලංකා තානාපති කාර්යාලය - වියනා',
    nameTa: 'இலங்கை தூதரகம் - வியன்னா',
    description: 'Sri Lankan Embassy in Austria',
    type: 'other',
    website: 'https://www.srilankaembassy.at',
    email: 'info@srilankaembassy.at',
    address: 'Weyringergasse 33-35, 1040 Vienna, Austria',
    formCount: 0,
    isActive: true,
  },
];
